#1 Employee refactor
Jacup/startupHorror pull request #22
Opened 2022-10-04 20:46 UTC by mrcombajn

2022-10-04 20:49 UTC, mrcombajn commented
What have been done at this moment:
- Sdded support of Maven, JUnit, Mockito, Lombok
- Implemented Lombok in classes

2022-10-06 20:20 UTC, Jacup requested changes

2022-10-06 20:20 UTC, Jacup commented on src/main/java/people/Owner.java
> -            projectsFound++;
Why projectsFound has been removed?

2022-10-06 20:20 UTC, Jacup commented on src/main/java/people/Owner.java
> -            projectsFound++;
hmm maybe it wasn't used rn...

2022-10-06 20:21 UTC, Jacup commented
Generally, i don't have idea what is going on, so I trust that you know what are you doing XD

2022-10-06 20:22 UTC, Jacup approved these changes

2022-10-06 20:22 UTC, merged